# Generated by Django 6.1 on 2026-08-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=20, unique=True)),
                ('prefix', models.CharField(choices=[('นาย', 'นาย'), ('น.ส.', 'น.ส.'), ('นาง', 'นาง')], max_length=10)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
            ],
        ),
    ]
