# Generated by Django 6.0.7 on 2026-08-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="prefix_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("นาย", "นาย"),
                    ("นาง", "นาง"),
                    ("นางสาว", "นางสาว"),
                    ("เด็กชาย", "เด็กชาย"),
                    ("เด็กหญิง", "เด็กหญิง"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
