# Generated by Django 6.0.7 on 2026-08-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_student_prefix_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="prefix_name",
            field=models.CharField(
                blank=True,
                choices=[("นาย", "นาย"), ("นาง", "นาง"), ("นางสาว", "นางสาว")],
                default="",
                max_length=20,
            ),
        ),
    ]
