# Generated by Django 6.0.7 on 2026-08-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_student_prefix_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mj_name', models.CharField(max_length=50)),
            ],
        ),
    ]
