# Generated by Django 6.0.7 on 2026-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_student_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
