# Generated by Django 6.0.7 on 2026-08-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_student1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student3",
            fields=[
                (
                    "st_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "prefix_name",
                    models.CharField(
                        blank=True,
                        choices=[("นาย", "นาย"), ("นาง", "นาง"), ("นางสาว", "นางสาว")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "major",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.major",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student4",
            fields=[
                (
                    "st_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "prefix_name",
                    models.CharField(
                        blank=True,
                        choices=[("นาย", "นาย"), ("นาง", "นาง"), ("นางสาว", "นางสาว")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "major",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.major",
                    ),
                ),
            ],
        ),
    ]
